// <auto-generated />
namespace LaptopWebSite.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EditdescriptionbecauseiamsetHTML : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditdescriptionbecauseiamsetHTML));
        
        string IMigrationMetadata.Id
        {
            get { return "201809201949527_Edit description because i am set HTML "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
